# Generated by Django 3.2.12 on 2022-07-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0002_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviehub.movie')),
            ],
        ),
    ]
