# Generated by Django 4.2 on 2024-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0003_yearcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(db_index=True),
        ),
        migrations.DeleteModel(
            name='YearCat',
        ),
    ]
