# Generated by Django 4.2 on 2024-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0004_station_alter_movie_desc_delete_yearcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='time',
            field=models.DateTimeField(default=True),
        ),
    ]
