# Generated by Django 4.2 on 2024-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviehub', '0005_alter_station_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='code',
        ),
        migrations.AddField(
            model_name='station',
            name='waiting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
